/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ScheduleDailyCollection': CronHandler<{ topic: 'data.collection.triggered'; data: never }>
    'QueryTaskLogsAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'QueryQuotesAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OnQuotesCollected': EventHandler<never, never>
    'OnCalendarUpdated': EventHandler<never, never>
    'ListTasksAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ExportDataAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CollectTradeCalendar': EventHandler<never, { topic: 'calendar.updated'; data: never }>
    'CollectDailyQuotes': EventHandler<never, { topic: 'quotes.collected'; data: never }>
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: number }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { id: string; quantity: number } }, ApiResponse<200, { id: number; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: number } }>
  }
}